interface date2ways {
  date_start: Date
  date_stop: Date
}

const dailyOrdersList = `SELECT 
SKUMASTER.SKU_CODE,
SKUMASTER.SKU_NAME,
SKUMASTER.SKU_E_NAME,
UOFQTY.UTQ_NAME,
UOFQTY.UTQ_QTY,
SKUMOVE.SKM_KEY,
SKUMOVE.SKM_LOT_NO,
SKUMOVE.SKM_SERIAL,
SKUMOVE.SKM_QTY,
SKUMOVE.SKM_Q_FREE,
SKUMOVE.SKM_COST,
SKUMOVE.SKM_SELL,
SKUMOVE.SKM_VAT,
SKUMOVE.SKM_EXP_D,
SKUMOVE.SKM_MAN_D,
SKUMOVE.SKM_SHOW_ORDER,
DOCTYPE.DT_THAIDESC,
DOCTYPE.DT_PROPERTIES,
SKUMASTER.SKU_PRICE,
SKUMASTER.SKU_EQ_FACTOR,
DI_DATE
FROM
SKUMOVE,
SKUMASTER,
UOFQTY,
DOCINFO,
DOCTYPE,
ICCAT,
BRAND,
ICDEPT,
APDETAIL,
APFILE,
APCAT,
TRANSTKH,
DEPTTAB,
BRANCH,
PRJTAB,
SHIPBY,
WARELOCATION,
WAREHOUSE
WHERE
SKUMOVE.SKM_SKU = SKUMASTER.SKU_KEY AND
SKUMASTER.SKU_S_UTQ = UOFQTY.UTQ_KEY AND
SKUMOVE.SKM_DI = DOCINFO.DI_KEY AND
SKUMOVE.SKM_WL = WARELOCATION.WL_KEY AND
WARELOCATION.WL_WH = WAREHOUSE.WH_KEY AND
DOCINFO.DI_DT = DOCTYPE.DT_KEY AND
DOCINFO.DI_ACTIVE = 0 AND
(DOCTYPE.DT_PROPERTIES = 301 OR 
DOCTYPE.DT_PROPERTIES = 303 OR 
DOCTYPE.DT_PROPERTIES = 304 OR 
DOCTYPE.DT_PROPERTIES = 336) AND
SKUMASTER.SKU_ICCAT = ICCAT.ICCAT_KEY AND
SKUMASTER.SKU_BRN = BRAND.BRN_KEY AND
SKUMASTER.SKU_ICDEPT = ICDEPT.ICDEPT_KEY AND 
DOCINFO.DI_KEY = APDETAIL.APD_DI AND
APDETAIL.APD_AP = APFILE.AP_KEY AND
APFILE.AP_APCAT = APCAT.APCAT_KEY AND
DOCINFO.DI_KEY = TRANSTKH.TRH_DI AND
TRANSTKH.TRH_DEPT = DEPTTAB.DEPT_KEY AND
TRANSTKH.TRH_BR = BRANCH.BR_KEY AND 
TRANSTKH.TRH_PRJ = PRJTAB.PRJ_KEY AND
TRANSTKH.TRH_SB = SHIPBY.SB_KEY AND
(DOCINFO.DI_DATE between '2020-06-15' AND '2020-06-16')
ORDER BY
SKUMASTER.SKU_KEY ASC`

const productList = `SELECT  SKU_CODE as skucode, 
SKU_KEY as skukey,
GOODS_CODE as  barcode, 
GOODS_KEY as barcode_key,
UTQ_QTY as bar_quantity,
UTQ_NAME as bar_unit,
SKU_NAME as skuname, 
ICDEPT_THAIDESC as department,
SKU_S_UTQ as quantity,                         
SKU_MIN_ORDER as min, 
SKU_MAX_ORDER as max,
GOODS_WEIGHT as weight,
GOODS_ENABLE as sales_enable,
GOODS_P_ENABLE as purchases_enable,
GOODS_MASTER as main_price,  
GOODS_VOLUME as volume,
GOODS_PRICE as control_price,
GOODS_ALIAS as alias_name,
GOODS_E_ALIAS as alias_name_eng
FROM GOODSMASTER
join SKUMASTER on SKU_KEY = GOODS_SKU
join ICDEPT on SKU_ICDEPT = ICDEPT_KEY
join UOFQTY on GOODS_UTQ = UTQ_KEY
ORDER BY SKU_KEY asc`

const doctypeList = `select DT_KEY as dtkey,
DT_DOCCODE as doccode,
DT_THAIDESC as dtthainame,
DT_ENGDESC as dtengname,
DT_PROPERTIES as properties,
DT_RUNTYPE as runtype,
DT_PREFIX as prefix,
DT_DIGIT as digit,
DT_VAT_PREFIX as vatref

from doctype order by dt_key asc`

export { productList, dailyOrdersList, doctypeList }
